name: stubble
description: Simplified version of the Handlebars template engine for Dart.
version: 1.1.1
homepage: https://github.com/Yohanson555/stubble4dart

environment:
  sdk: ">=2.14.2 <3.0.0"
dependencies:
  meta: ^1.1.8

dev_dependencies:
  lints: ^1.0.1
  test: ^1.25.8
