part of stubble;

const ROOT_STATE = 0;
const AWAITING_SECOND_OPEN_BRACER = 1;
const AWAITING_SECOND_CLOSE_BRACER = 7;
const AWAITING_SEQUENCE_CHARACTER = 2;
const AWAITING_PATH_NAME = 3;
const AWAITING_HELPER_NAME = 4;
const AWAITING_BLOCK_NAME = 5;
const AWAITING_ATTRIBUTE = 8;
const AWAITING_PATH = 9;
const AWAITING_IF_BODY = 101;
const AWAITING_WHICH_BODY = 102;
const AWAITING_BLOCK_BODY = 103;
const AWAITING_IF_END_OR_ELSE = 104;
const AWAITING_IF_END = 105;
const AWAITING_WHICH_END = 106;
const AWAITING_BLOCK_END = 107;
const ESCAPE_CHARACTER = 1000;