part of stubble;

const ERROR_CHAR_NOT_A_OPEN_BRACKET = 1;
const ERROR_CHAR_NOT_A_CLOSE_BRACKET = 2;
const ERROR_NOT_A_VALID_BLOCK_NAME_CHAR = 3;
const ERROR_NOT_A_VALID_PATH_CHAR = 4;
const ERROR_WRONG_SEQUENCE_CHARACTER = 5;
const ERROR_WRONG_DATA_SEQUENCE_CHARACTER = 6;
const ERROR_PATH_WRONG_SPECIFIED = 7;
const ERROR_BLOCK_NAME_WRONG_SPECIFIED = 8;
const ERROR_CALLING_HELPER = 9;
const ERROR_GETTING_ATTRIBUTE = 10;
const ERROR_NUMBER_ATTRIBUTE_MALFORMED = 11;
const ERROR_UNSUPPORTED_NOTIFY = 12;
const ERROR_PATH_NOT_SPECIFIED = 13;
const ERROR_WITH_DATA_MALFORMED = 14;
const ERROR_IF_BLOCK_MALFORMED = 15;
const ERROR_IF_BLOCK_CONDITION_MALFORMED = 16;